### ISSUE TITLE
Merging HybridAuth into A3M for better service support

### ISSUE THREAD

**Issue by dovy** [pengkong/A3M-for-CodeIgniter-2.0#24]
I LOVE A3M, but the auth libraries don't always work. So I am thinking of integrating HybridAuth (http://hybridauth.sourceforge.net/) into A3M. This would allow for another project to manage the oauth integrations, and A3M be focused on the account management, etc. Thoughts?

There's already a project integrating Codeigniter with HybridAuth (https://github.com/andacata/HybridIgniter/), but it's very basic and I want the account features of A3M. I think for the A3M portion though, we'll bypass this library but maybe use parts of their controller.

Would anyone like to work with me on this? I will begin work on this next week. Would it be received well?

**Comment by donjakobo** [comment]
I have a plan (but am short on time) to re-write A3M to make it 'easier' to use.  Currently I have my own A3M working beautifully without username/passwords, and without the modularized approach (separate module loads).  My application keeps the controllers / libraries in the `/application` root, and not under modules

I don't know if there is any reason to 'combine' A3M with HybridAuth, as they do the same thing.  You are better off combining or intergrating HybridAuth as a CI plugin (IMHO better time spent).

**Comment by dovy** [comment]
Donjakobo:
HybridAuth is already a CI Plugin, but I want the account creation/management/linking setup. That's what I need. Any thoughts?

**Comment by donjakobo** [comment]
Sorry, late reply, I've been really busy... I don't know what to tell you, your goal is to use _HybridAuth_ because you like the extra connectors, but you hate that it doesn't have backend functionality in place like _A3M_.  Its simply a trade-off that isn't bridged by either solution at this point in time.

My only suggestion is, I encourage you to try to write it, and contribue back.  I hope people contribute more to a3m, as I took this over from someone else too.

I did work on a re-write of a3m tho, using twitter bootstrap (easy ui modifications) and freeing it from the pain in the ass modules folder structure (imho).  These things should make a3m more flexible and easier to use and modify in the future.
