### ISSUE TITLE
Facebook redirect loop

### ISSUE THREAD

**Issue by mwo44** [pengkong/A3M-for-CodeIgniter-2.0#6]
Not sure if I'm addressing the problem correctly.
I managed to get A3M up and running, but sometimes when I try both to sign up and to sign in with facebook I get a redirect loop error. I tried both running my with www. and just domain but the problem occurs, being logged out and logged in in FB and it still occurs.

**Comment by donjakobo** [comment]
The redirect loop is **actually** due to your setup of FB. Make sure the URL in your facebook application is the **same**  as your url that you are logging into, (www/non-www counts!).  The loop only happens when you setup your primary host (ie: www.myhost.com) and then you try logging in on your development setup (ie: dev.home.myhost.com:8080/)

I've experienced that before, fix the url or only login on your primary site for it to go away.  Actually the redirect is DUE to facebook telling you "sorry can't authenticate this isn't the proper redirect url you sent us", its just too quick for you to see.

**Comment by mwo44** [comment]
Thanks for help,
I think I found what's causing the problem.
When I use .htaccess to remove index.php from my codeigniter url the redirect loop occurs. But when I link FB button with full link index.php/account/connect_facebook everything seems to work correctly.

**Comment by bark** [comment]
Hi i belive i got the same problem.
How did you solve it?
my configure is for the moment:
.htacess: http://pastebin.com/ryyjHweL
url to test site:
http://dev.metapic.se/account/connect_facebook
and on facebook i have configure:
Website with Facebook Login: http://dev.metapic.se/account/connect_facebook
and a get a redirectloop when i try that link.
i have tried whit the link:
http://dev.metapic.se/index.php/account/connect_facebook
But it is no diffrent there.
